### PR TITLE
A few section/speaker related bits

### PR DESCRIPTION
**Pull request by dracos**
Simplify the forms, use /section instead of /sections and use any sort_names present for sorting.

### CODE REVIEW

**Comment by girogiro** [comment]
Speakers are now sorted by sort_name on the `/speakers` page, but the shown names do not correspond to the sort order. It is a bit confusing for the user. What about using
```
{% if speaker.sorted_name %}{{ speaker.sorted_name }}{% else %}{{ speaker }}{% endif %}
```
in the `speaker_list` template?

**Comment by dracos** [comment]
Hi @girogiro – I'm not sure that would work, in a common situation anyway. If your speaker names are "Matthew Aardvark", "Eve Badger" and "Jaroslav Capybara", and you wanted them to display in alphabetical order by surname, then you would set their `sort_name`s to be "Aardvark, Matthew", "Badger, Eve" and "Capybara, Jaroslav". You wouldn’t want to display those `sort_name`s though, as they’re not as friendly. What are you putting in `sort_name` such that it is proving confusing?

**Comment by girogiro** [comment]
I mean exactly the situation you described. A long list of speakers is a bit easier to scan by eye and find a desired name (at least for me) when you see:

Aardvark, Matthew,
Badger, Eve
Capybara, Jaroslav

instead of:

Matthew Aardvark
Eve Badger
Jaroslav Capybara

even though the order is identical.

**Comment by dracos** [comment]
Interesting :) http://www.theyworkforyou.com/mps/ is ordered by last name, but displays "first last"; in comparison the official site at http://www.parliament.uk/mps-lords-and-offices/mps/ displays "last, first" and I always found that harder to parse. Wikipedia tables sort by surname but display "first last" e.g. https://en.wikipedia.org/wiki/Current_members_of_the_United_States_House_of_Representatives#Voting_members_by_state (click Name). Both iPhone and Android let you pick both display and sort order separately either way.

**Comment by dracos** [comment]
You may have speakers that have a starting "The", e.g. "The Minister for Housing", and I personally wouldn't want that to display as "Minister for Housing, The" or "Housing, The Minister for" (depending on how you might want to have it display). This certainly seems like something that different users may want to have differently, so we should probably try and have some form of configuration variable to pick the display version – perhaps as an argument to the `SpeakerList` view, if not a main configuration variable.

**Comment by girogiro** [comment]
OK, seems to be a matter of personal taste. I thought it to be a more universal assumption that scanning by prefix of the displayed name is easier than by prefix of the last word (as you are usually searching by surname). :)  But it is not a superimportant feature.

In Slovakia we usually use "First Last", but in alphabetical lists the "Last First" or "Last, First" form is more often used.

**Comment by dracos** [comment]
I've added a ticket at https://github.com/mysociety/sayit/issues/458 :)

**Pull request merged**
